#!/bin/bash
set -euo pipefail

# Regenerate Exasol copies of upstream dbt_utils test models.
#
# Upstream models name CTEs `data` or `source`, which are reserved words in Exasol.
# This script copies each such model to models/dbt_utils_overrides/<dir>/ and renames
# the CTE (data -> test_data, source -> source_data). Generated files start with
# GENERATED_MARK. Hand-written copies (no mark) are never overwritten.
#
# It then rewrites the block between the BEGIN/END markers in dbt_project.yml, which
# disables every upstream model that has a local copy.
#
# Run after `dbt deps` whenever the dbt_utils version changes.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

UPSTREAM="dbt_packages/dbt_utils/integration_tests/models"
LOCAL="models/dbt_utils_overrides"
DIRS="datetime generic_tests geo sql"
GENERATED_MARK="-- Generated by create_overrides.sh from upstream dbt_utils. Do not edit."

if [ ! -d "$UPSTREAM" ]; then
  echo "Missing $UPSTREAM. Run dbt deps first." >&2
  exit 1
fi

# Remove old generated copies, so models that no longer need a copy disappear
{ grep -rlF -- "$GENERATED_MARK" "$LOCAL" 2>/dev/null || true; } | xargs rm -f

for dir in $DIRS; do
  for src in "$UPSTREAM/$dir"/*.sql; do
    name="$(basename "$src")"
    dest="$LOCAL/$dir/$name"
    grep -qiE '^\s*(with\s+)?(data|source)\s+as\s*\(' "$src" || continue
    if [ -f "$dest" ]; then
      echo "keep   $dest (hand-written)"
      continue
    fi
    mkdir -p "$LOCAL/$dir"
    # Upstream SQL comments are dropped: they refer to other adapters and do not apply here
    { echo "$GENERATED_MARK"; perl -ne 'next if /^\s*--/; s/\bdata\b/test_data/g; s/\bsource\b/source_data/g; print' "$src"; } > "$dest"
    echo "create $dest"
  done
done

# Rebuild the disable list from every local copy that has an upstream original
block="$(
  for f in "$LOCAL"/*/*.sql; do
    dir="$(basename "$(dirname "$f")")"
    name="$(basename "$f" .sql)"
    [ -f "$UPSTREAM/$dir/$name.sql" ] && echo "    $name: {+enabled: false}"
  done | sort
)"
python3 - "$block" <<'EOF'
import re, sys
p = "dbt_project.yml"
s = open(p).read()
new = "    # BEGIN create_overrides.sh\n" + sys.argv[1] + "\n    # END create_overrides.sh"
s, n = re.subn(r"    # BEGIN create_overrides\.sh\n.*?    # END create_overrides\.sh", lambda m: new, s, flags=re.S)
if n != 1:
    sys.exit("dbt_project.yml: BEGIN/END create_overrides.sh markers not found")
open(p, "w").write(s)
EOF
echo "updated disable list in dbt_project.yml"
