exasol:
  target: prod
  outputs:
    prod:
      type: exasol
      dsn: "{{ env_var('EXA_DSN', 'localhost:8563') }}"
      user: sys
      password: exasol
      dbname: DB
      schema: dbt_test
      timestamp_format: "YYYY-MM-DD HH:MI:SS.FF6"
      validate_server_certificate: false
      threads: 4
