-- Generated by create_overrides.sh from upstream dbt_utils. Do not edit.
with test_data as (

    select * from {{ ref('data_test_fewer_rows_than_table_1') }}

)

select
   col_a, field
from test_data