-- Generated by create_overrides.sh from upstream dbt_utils. Do not edit.
{% set exclude_field = 'field_3' %}


with test_data as (

    select
        {{ dbt_utils.star(from=ref('data_star'), except=[exclude_field]) }}

    from {{ ref('data_star') }}

)

select * from test_data
