-- Generated by create_overrides.sh from upstream dbt_utils. Do not edit.

with test_data as (

    select * from {{ ref('data_safe_subtract') }}

)

select
    {{ dbt_utils.safe_subtract(['field_1', 'field_2', 'field_3']) }} as actual,
    expected

from test_data
