-- Generated by create_overrides.sh from upstream dbt_utils. Do not edit.

with test_data as (

    select * from {{ ref('data_width_bucket') }}

)

select
    {{ dbt_utils.width_bucket('amount', 'min_value', 'max_value', 'num_buckets') }} as actual,
    bucket as expected

from test_data
