-- Generated by create_overrides.sh from upstream dbt_utils. Do not edit.


{{ config(materialized='table') }}

with test_data as (

    {{ dbt_utils.generate_series(10) }}

)

select generated_number from test_data
