-- Generated by create_overrides.sh from upstream dbt_utils. Do not edit.
with

source_data as (
    select *
    from {{ ref('data_deduplicate') }}
    where user_id = 1
),

deduped as (

    {{
        dbt_utils.deduplicate(
            'source_data',
            partition_by='user_id',
            order_by='version desc',
        ) | indent
    }}

)

select * from deduped
