-- Generated by create_overrides.sh from upstream dbt_utils. Do not edit.
with test_data as (

    select
        {{ dbt_utils.star(from=ref('data_star'), except=['field_1', 'field_2', 'field_3']) }}
        1 as canary_column
    from {{ ref('data_star') }}

)

select * from test_data
